// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/detail-bill/{bill-id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "receipts"
                ],
                "summary": "Get Receipts By User ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetAllByIdResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GetAllByIdResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "Makanan"
                },
                "receipts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReceiptDTO"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Toko Test"
                },
                "total": {
                    "type": "number",
                    "example": 38850
                }
            }
        },
        "ProductDTO": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "number",
                    "example": 0
                },
                "id": {
                    "type": "string",
                    "example": "f5063dca-556c-4723-931b-cbade7ca139a"
                },
                "price": {
                    "type": "number",
                    "example": 15000
                },
                "product_name": {
                    "type": "string",
                    "example": "bakso"
                },
                "quantity": {
                    "type": "integer",
                    "example": 1
                },
                "service": {
                    "type": "number",
                    "example": 0
                },
                "tax": {
                    "type": "number",
                    "example": 11
                }
            }
        },
        "ReceiptDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "f5063dca-556c-4723-931b-cbade7ca139a"
                },
                "name": {
                    "type": "string",
                    "example": "adit"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ProductDTO"
                    }
                },
                "total": {
                    "type": "number",
                    "example": 16650
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
